artifacts_root : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts

data_ingestion:
  root_dir: C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_ingestion\\data.zip
  unzip_dir : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_ingestion

data_validation:
  root_dir: C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_validation
  unzip_data_dir : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_ingestion\\winequality-red.csv
  STATUS_FILE : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_validation\\status.txt

data_transformation:
  root_dir: C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_transformation
  data_path : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_ingestion\\winequality-red.csv

data_training:
  root_dir :  C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\model_trainer
  train_data_path: C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_transformation\\train.csv
  test_data_path : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_transformation\\test.csv
  model_name: model.joblib

model_evaluation:
  root_dir : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\model_evaluation
  test_data_path : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\data_transformation\\test.csv
  model_path : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\model_trainer\\model.joblib
  metric_file_name : C:\\Users\\Damini.gupta\\PycharmProjects\\datascienceproject\\artifacts\\model_evaluation\\metrics.json




